textileio/community

docs/learn/threads/files/mills.md

Currently is being rendered like so:

docs: fix rendering of endpoint listing

---

docs/a-tour-of-textile.md
snippets/a_tour_of_textile.yml
snippets/common.yml

Fixes: #33. I think we now have parity with `cmd`wherever possible. There are probably a few points where the streaming API endpoints could be better outlined, but these are hard to 'show' in short snippets. Especially if we are trying to demo the similarities. I've added references where needed. I'll also create some gists with examples that we can link to I think.

Validate all js-client snippets + adds missing ones

---

README.md

The workflow for serving and deploying docs uses a Makefile. On Windows machines, make isn't available by default, even when using Git Bash. I added a note explaining that Windows users will need to install Make themselves, and linked to a guide to installing make on Git Bash.

Added information about installing make on Windows

---

docs/connectors/documents/index.md
mkdocs.yml

Signed-off-by: andrew <andrewxhill@gmail.com>
not as fully flushed out as the images one, but i think it's a good start to help point someone the right direction. also now connectors with an 's' is correct in the menu. ha.

Adds a basic document connector to get us started

---

docs/develop/clients/react-native.md

went through and updated the old boilerplate to use new releases, https://github.com/textileio/advanced-react-native-boilerplate/pull/3/
figured we should make it available in the docs.

adds link to boilerplate

---

mkdocs.yml

currently we are falling back to gh default 404 which isn't helpful because you can't easily navigate to a real docs page. updates to,

adds 404 page back to statics

---

docs/connectors/images/index.md

Under `connectors/images & media` the desktop photos app link has been updated in the `Apps & Demos` section.

Fix broken desktop photos app link

---

snippets/common.yml

--profile-bind-addr parameter was missing which leaded to an error when 2 daemons tried to run with the same profile bind default addr.

Fix incomplete textile init command

---

docs/develop/clients/android.md
docs/develop/clients/ios.md
docs/develop/clients/javascript.md
docs/develop/clients/react-native.md
snippets/common.yml

Add raw ipfs pubsub pub and sub to [Expose simple p2p direct message API](https://github.com/textileio/go-textile/issues/885)
Related PR:
[js-http-client: add raw ipfs pubsub pub and sub from go-textile v0.7.6](https://github.com/textileio/js-http-client/pull/137)
[react-native-sdk: add raw ipfs pubsub pub and sub from android 2.0.10 and ios 2.0.12 and go-textile v0.7.6](https://github.com/textileio/react-native-sdk/pull/161)

docs: add raw ipfs pubsub pub and sub from go-textile v0.7.6

---

docs/powergate/devnet.md

- Specifies the volume binding so you can import files easily.
- A bit more explanation about devnet configuration.
- Other nit.

devnet: bind container volume, explain configs, building advice

---

docs/powergate/devnet.md

It explains a bit better some important things about auto-funding, and big sectors file sizes. The latter mostly an adaptation of what said in the blogpost.

autofunding and bigsectors notes

---

docs/powergate/localnet.md
docs/powergate/testnet.md

We had some stalled docs reg the bigsectors problem.
Also adds some rough explanation of how to `make up` from a snapshot. Docker makes this a bit cumbersome, but tbh is just changing two lines. Automating this in a command requires some thought for reasons I could explain.
That's good enough for now.

update bigsectors && explain boostrap from snapshot

---

docs/hub/apis.md

The link to the CLI docs here at the bottom of this page (https://docs.textile.io/hub/apis/#api-libraries) goes to `https://docs.textile.io/hub/hub/cli/hub` which 404s, I believe this fixes it.

Fix broken link to hub cli docs

---

docs/powergate/testnet.md

Change CAR snsapshot link to a pruned version which should be smaller than full snapshot.

change CAR file link to pruned version

---

docs/buckets/archiving.md
docs/powergate/faq.md
docs/powergate/index.md
docs/powergate/mainnet.md
mkdocs.yml

fix(mainnet): update powergate docs for mainnet

---

.github/workflows/test.yml
docs/hub/cli/hub.md
docs/hub/cli/hub_buck_init.md
docs/hub/cli/hub_fil.md
docs/hub/cli/hub_fil_sign.md
docs/hub/cli/hub_fil_verify.md
docs/powergate/cli/pow_storage-jobs.md
docs/powergate/cli/pow_storage-jobs_cancel-executing.md
docs/powergate/cli/pow_storage-jobs_cancel-queued.md

Getting things up to date with the latest cli docs from hub and powergate.

Hub 2.4.0 update

---

docs/hub/miner-index.md

"notes" → "nodes" and "start" → "store"
cc: @andrewxhill

Fix two typos

---

docs/tutorials/hub/pki-identities.md

Fix typo: `ed2559` -> 'ed25519`

Fix 25519 typo

---

docs/index.md
mkdocs.yml

adds links to eth.storage and near.storage right to the top of the entry point

fix(docs): adds new links to bridges

---

docs/docs/threads/index.md

I believe I found a typo in the docs for threads.  Not sure what the original author was trying to say, but I think they meant to use the word "layer" not "later"

Potentially fix typo in Threads docs
