docs/a-tour-of-textile.md, docs/concepts/cafes.md
Also adds a section with the new dev cafe's details.
fixes #23
=> cafes: add host and client section

a_tour_of_textile.yml, docs/a-tour-of-textile.md
a few still missing as todos plus some are a bit out of sync with improved api sigs
opened a bunch of tickets to get it aligned
=> tour: adds react native snippets

docs/clients/js-http.md, mkdocs.yml, snippets/a_tour_of_textile.yml, snippets/common.yml
moves non tour specific code snippets to a common.yml, then reuses those in a simple JS HTTP Client getting started document.
=> JS getting started yaml

docs/clients/js-http.md, docs/clients/react-native.md, snippets/common.yml
@asutula maybe worth skimming this over, especially the setups steps for ios/android
=> Adds react native getting started

docs/clients/react-native.md
Signed-off-by: andrew <andrewxhill@gmail.com>
=> fixes android module install

docs/a-tour-of-textile.md
Just a little thing that I thought might prevent a small hang-up for users going through the tour line by line.
=> Clarify a potential hang-up

docs/a-tour-of-textile.md, snippets/a_tour_of_textile.yml
Fixes #62. Includes some explanatory notes and typo fixes as well.
=> Tour of Textile Formatting Fixes

docs/a-tour-of-textile.md, docs/connectors/images/index.md, snippets/a_tour_of_textile.yml, snippets/common.yml
=> renames all "ios" tabs to "obj-c"

docs/a-tour-of-textile.md, docs/develop/clients/js-http.md, snippets/common.yml
Signed-off-by: andrew <andrewxhill@gmail.com>
Been a number of related questions lately, so better if we can answer with some docs.
=> adds some clarity around adding/getting files in node vs browser

docs/develop/clients/ios.md, docs/develop/clients/js-http.md, snippets/common.yml, snippets/connectors.yml
Signed-off-by: andrew <andrewxhill@gmail.com>
Snippets paid off here for sure!
=> Basic iOS introduction

docs/a-tour-of-textile.md, docs/develop/clients/android.md, docs/develop/clients/ios.md, snippets/a_tour_of_textile.yml, snippets/common.yml
Closes #35 
@andrewxhill This should be good to go, but I'm having trouble running `make setup` so I can't test it locally. Something going wrong when it tries to install `mkdocs-codeyaml-plugin`. Maybe my python version or something, no idea. Anyway, take a look and test it out etc.
=> Android snippets

docs/a-tour-of-textile.md, docs/develop/clients/command-line.md, docs/develop/ipfs-gateway.md, docs/develop/the-http-api.md, docs/install/the-daemon.md, scripts/build
Fixes #32 
Fixes #37 
Also updates HTTP docs and command-line docs.
=> Redactions, new decrypting gateway example

docs/develop/clients/command-line.md, scripts/build
- Workarounds https://github.com/Python-Markdown/markdown/issues/830
- Closes https://github.com/textileio/docs/issues/95
- References https://github.com/textileio/go-textile/pull/847
Signed-off-by: Benjamin Lupton <b@lupton.cc>
=> update docs for v0.6.1

snippets/common.yml
=> Update init examples to latest api, some editor auto fixes

snippets/common.yml
Signed-off-by: Carson Farmer <carson.farmer@gmail.com>
=> update to latest tokens api

docs/a-tour-of-textile.md
Some improvements based on a discussion in Slack.
=> tour: fixes & clarifications

docs/a-tour-of-textile.md, docs/concepts/cafes.md, docs/concepts/contacts.md, docs/concepts/threads/index.md, docs/develop/clients/command-line.md, snippets/common.yml
Signed-off-by: andrew <andrew@textile.io>
=> adds warning about upcoming threads v2 release

docs/develop/clients/android.md, docs/develop/clients/command-line.md, docs/develop/clients/ios.md, docs/develop/clients/javascript.md, docs/develop/clients/react-native.md
=> add warnings and new lib links to client sections

docs/hub/app-apis.md
=> fix(keys): fixes user key blurb

docs/hub/app-apis.md, docs/hub/buckets.md, docs/index.md
=> docs: IFPS --> IPFS

docs/threads/introduction.md, notebooks/Database.ipynb
Some restructuring here as well to facilitate a literate code/explainer style.
=> Update database examples w/ working code

docs/hub/buckets.md, docs/index.md, docs/policies/privacy.md, docs/tutorials/react-native-buckets.md, mkdocs.yml, notebooks/Database.ipynb, notebooks/Hub.ipynb
Signed-off-by: andrew <andrew@textile.io>
=> feat(tutorials): adds rn

.github/workflows/deploy.yml, .textile/config.yml, docs/hub/buckets.md, docs/index.md, docs/tutorials/static-websites.md, mkdocs.yml, scripts/setup
Signed-off-by: andrew <andrew@textile.io>
=> feat(ci): adds bucket deployment

docs/powergate/devnet.md
=> feat(docs): add note about devnet miner addresses

docs/hub/buckets.md, docs/hub/cli/hub_buck_init.md
Related to this [merged PR](https://github.com/textileio/textile/pull/231).
=> mention buck init and buck add new features

docs/index.md, docs/powergate/index.md
=> fix(pow): main docs page was out of date on pow resources

docs/threads/index.md
This should complete the list of examples. They should now all compile/build correctly. Thanks for the huge effort to get this going @andrewxhill!
=> Update all db examples to ensure ts compiles

docs/powergate/devnet.md, docs/powergate/ffs.md, docs/powergate/testnet.md, mkdocs.yml
=> chore(pow): adds a bit more content and org for powergate

docs/powergate/devnet.md, docs/tutorials/hub/user-login-endpoint.md, scripts/test, test/package.json, test/src/index.ts, test/tsconfig.json
Signed-off-by: Aaron Sutula <hi@asutula.com>
=> couple little fixes

docs/hub/accounts.md, docs/powergate/ffs.md, docs/tutorials/golang/getting-started.md, mkdocs.yml
slipped in a couple `tt` fixes
slipped in a few bits of pow language based on support questions
=> chore(golang): adds intro tutorial for using golang with the hub

docs/buckets/index.md, docs/hub/accounts.md, docs/hub/app-apis.md, docs/hub/index.md, docs/index.md, docs/tutorials/react-native-buckets.md, material/partials/nav-item.html, mkdocs.yml
=> chore(buckets): move buckets to top level organization

docs/powergate/index.md
Similar to [README](https://github.com/textileio/powergate/pull/478) changes.
=> pow: clarify compiling nits

.github/workflows/test.yml, docs/hub/app-apis.md, docs/tutorials/hub/libp2p-identities.md, mkdocs.yml, test/src/index.ts, test/tsconfig.json
=> feat(3box): extends identity section with simple 3box example

docs/hub/app-apis.md, docs/tutorials/hub/simple-credentials-endpoint.md, docs/tutorials/hub/user-login-endpoint.md, docs/tutorials/hub/web-app.md, docs/tutorials/react-native-buckets.md
=> chore(docs): udpate keyinfo/userauth docstrings

docs/hub/app-apis.md, docs/tutorials/hub/development-mode.md, docs/tutorials/hub/user-buckets.md, docs/tutorials/hub/user-thread-database.md, docs/tutorials/hub/web-app.md, mkdocs.yml, test/package.json
This is a WIP. A couple requirements to wrap it up.
release https://github.com/textileio/js-threads/pull/373
add https://github.com/textileio/js-threads/issues/381
=> feat(chat): adds a chat app tutorial

docs/buckets/index.md
This is me just adding @sanderpick explanation about buckets encryption, which I think is very valuable to put some light on this feature. Maybe eventually might deserve its own section.
=> encryption section

docs/tutorials/hub/user-thread-database.md, mkdocs.yml
=> feat(db): adds links and description of local db example

docs/powergate/localnet.md
Updates considering https://github.com/textileio/powergate/pull/572
=> explain bigsectors new default and limitation

docs/tutorials/golang/getting-started.md, docs/tutorials/hub/production-auth.md, docs/tutorials/hub/user-buckets.md
=> fix(terms): remove mention of sessions over sigs

docs/threads/index.md, test/src/index.ts
=> fix(js): updates js examples with new api sigs

docs/powergate/ffs.md
👋 friends! Taking a quick spin through your docs, thought I'd try to help
=> small fixes & cleanups to 'Intro to FFS'

docs/powergate/faq.md, docs/powergate/ffs.md, mkdocs.yml
Powergate FAQs gathered by some days of doing support in #powergate-users.
I'm not completely sure if using `code quotes` in ## sections is going to be rendered nicely. 
Maybe there is a better-known strategy?
Anything extra apart from editing `mkdocs` for including this new file?
=> Powergate FAQs

docs/buckets/index.md, docs/buckets/permissions.md, docs/hub/apis.md, docs/hub/development.md, docs/index.md, docs/threads/index.md, docs/tutorials/hub/pki-identities.md, docs/tutorials/hub/user-buckets.md, docs/users/index.md, mkdocs.yml, scripts/contributors/update.py
=> fix(docs): js-hub => js-textile

docs/powergate/storageconfig.md, mkdocs.yml
=> MaxPrice desc

docs/powergate/mainnet.md
Signed-off-by: Ignacio Hagopian <jsign.uy@gmail.com>
=> pow: import snapshot, update car name and screenshot

docs/users/index.md
Edited the user mailboxes md file.
Signed-off-by: yongelee <albertkim91@gmail.com>
=> edited User Mailboxes docs

docs/threads/index.md
Edited the ThreadsDB overview docs page. 
Signed-off-by: yongelee <albertkim91@gmail.com>
=> edited threadsdb md file

.github/workflows/deploy.yml, docs/index.md
=> chore(hub): move docs bucket to textile org

docs/buckets/permissions.md
Easy navigation and easy reading for others
=> chore(docs): Fix broken url in docs

mkdocs.yml
=> fix(sidebar): adds new cli methods. 

docs/hub/cli/hub.md, docs/hub/cli/hub_buck_archive.md, docs/hub/cli/hub_buck_archive_set-default-config.md, docs/hub/cli/hub_fil.md, docs/hub/cli/hub_fil_index.md, docs/hub/cli/hub_fil_index_calculate.md, docs/hub/cli/hub_fil_index_get.md, docs/hub/cli/hub_fil_index_query.md, docs/hub/cli/hub_fil_info.md, docs/powergate/cli/pow_deals_retrievals.md, docs/powergate/cli/pow_deals_storage.md
perhaps should re-run after https://github.com/textileio/textile/pull/518
=> feat(cli): adds miner index docs

docs/hub/miner-index.md, mkdocs.yml
=> feat(index): adds a live landing page to the index

docs/hub/apis.md, docs/index.md, docs/tutorials/go/getting-started.md, mkdocs.yml, scripts/contributors/update.py
=> fix(links): use new go-buckets repo

docs/tutorials/go/getting-started.md
=> fix(go): fixes go thread client setup instructions

docs/filecoin/balances.md, docs/filecoin/miner-index.md, docs/filecoin/storage-deals.md, mkdocs.yml
=> feat(docs): adds some pages to fill out filecoin commands

docs/powergate/offline.md
Adds documentation for new features introduced in https://github.com/textileio/powergate/pull/820
=> pow: offline deals docs

docs/powergate/offline.md
Somewhat rough.
Already opening for review. I'll merge when this lands on a `powergate` release tomorrow.
=> pow: offline aggregator CLI mode

docs/hub/pricing.md
Three "s" letters in egress instead of two.
=> Spelling error

docs/docs/index.md
Thanks to @OneTenDigital for finding this
=> Fix #300 typo in docs docs

docs/docs/powergate/index.md
=> Fix: Typo in Powergate intro

docs/docs/hub/accounts.md
Adds instructions how to install the hub for linux
=> feat(hub): add install instructions for linux
